# Generated by Django 4.2.8 on 2026-01-23 22:10

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_type', models.CharField(choices=[('player', 'Player'), ('team', 'Team')], max_length=10)),
                ('faceit_nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TeamProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('looking_for_igl', models.BooleanField(default=False)),
                ('looking_for_awper', models.BooleanField(default=False)),
                ('needed_positions', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faceit_player_id', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=10)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('elo', models.IntegerField(blank=True, null=True)),
                ('skill_level', models.IntegerField(blank=True, null=True)),
                ('faceit_url', models.URLField(blank=True)),
                ('avatar', models.URLField(blank=True)),
                ('matches', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('win_rate', models.FloatField(default=0.0)),
                ('average_kd', models.FloatField(default=0.0)),
                ('average_hs', models.FloatField(default=0.0)),
                ('current_win_streak', models.IntegerField(default=0)),
                ('longest_win_streak', models.IntegerField(default=0)),
                ('is_igl', models.BooleanField(default=False)),
                ('can_awp', models.BooleanField(default=False)),
                ('mirage_ct_position', models.CharField(blank=True, max_length=50)),
                ('dust2_ct_position', models.CharField(blank=True, max_length=50)),
                ('anubis_ct_position', models.CharField(blank=True, max_length=50)),
                ('nuke_ct_position', models.CharField(blank=True, max_length=50)),
                ('ancient_ct_position', models.CharField(blank=True, max_length=50)),
                ('inferno_ct_position', models.CharField(blank=True, max_length=50)),
                ('overpass_ct_position', models.CharField(blank=True, max_length=50)),
                ('t_role', models.CharField(blank=True, choices=[('lurker', 'Люркер'), ('entry', 'Ентри'), ('support', 'Сапорт')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('steam_id', models.CharField(blank=True, max_length=50)),
                ('last_faceit_update', models.DateTimeField(blank=True, null=True)),
                ('profile_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
