# Generated by Django 6.0.1 on 2026-01-28 10:14

import faceit_analytics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceit_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heatmapaggregate',
            name='image',
            field=models.FileField(blank=True, upload_to=faceit_analytics.models.heatmap_upload_to),
        ),
    ]
