# Generated by Django 4.2.8 on 2026-01-28 14:48

from django.db import migrations, models
import faceit_analytics.models


class Migration(migrations.Migration):

    dependencies = [
        ('faceit_analytics', '0004_heatmap_aggregate_v1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heatmapaggregate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='heatmapaggregate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=faceit_analytics.models.heatmap_upload_to),
        ),
    ]
