# Generated by Django 4.2.8 on 2026-01-28 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("faceit_analytics", "0005_alter_heatmapaggregate_created_at_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="heatmapaggregate",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="heatmapaggregate",
            name="metric",
            field=models.CharField(
                choices=[("kills", "Kills"), ("deaths", "Deaths")],
                default="kills",
                max_length=10,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="heatmapaggregate",
            unique_together={
                (
                    "profile",
                    "map_name",
                    "metric",
                    "side",
                    "period",
                    "analytics_version",
                    "resolution",
                )
            },
        ),
    ]
