# Generated by Django 4.2.8 on 2026-01-29 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faceit_analytics', '0008_alter_heatmapaggregate_metric'),
        ('faceit_analytics', '0008_normalize_heatmap_values'),
    ]

    operations = [
    ]
